defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: encoder_decoder_only
- model: transformer
- training: default
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1



diagnostics:
  log:
    mlflow:
      enabled: False
      offline: False
      terminal: True
      tracking_uri: 'http://your-mlflow-server:5000'
    wandb:
      enabled: False
      entity: None

hardware:
  accelerator: auto
  num_nodes: 1
  num_gpus_per_model: 1
  paths:
    data: "/home/mlx/ai-ml/datasets/"
    output: "./output_training/"
    graph: "./graphs/"
    warm_start: "/ec/res4/hpcperm/nld4584/Anemoi_S2S_experiment/checkpoints_mariana/louca/"
  files:
    dataset: aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr
    graph: graph.pkl
    warm_start: last.ckpt
  

model:
  num_channels: 1024

data:
  normalizer:
    default: "mean-std"

dataloader:
  limit_batches:
    training: null
    validation: 100

training:
  max_epochs: 50
  max_steps: 300
  lr:
    rate: 6.25e-5 # tests
    iterations: 300000
    min: 3e-7 #Not scaled by #GPU

  training_loss:
    _target_: anemoi.training.losses.PINNmse.PINNMSELoss
    physics_weight: 1.0
    alpha: 0.5
    dataset_path: "/home/mlx/ai-ml/datasets/aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr"
    scalers: ['pressure_level', 'general_variable', 'nan_mask_weights', 'node_weights']


